name: epub_plus
description: Epub Parser for dart. Works on server, web or flutter. Refactored and heavily tested fork. 
homepage: https://github.com/renanyoy/epub_plus
issue_tracker: https://github.com/renanyoy/epub_plus/issues
version: 6.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ">=3.4.10 <5.0.0"
  path: ">=1.9.0 <2.0.0"
  xml: ">=6.4.0 <7.0.0"
  image: ">=4.0.0 <5.0.0"
  collection: ">=1.18.0 <2.0.0"

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
